In [6]:
%load_ext autoreload
%autoreload 2

from pad_autoencoder import DataGenerator, autoencoder, inputModel
import numpy as np
from tensorflow import keras
from scraperTools import getDataFromFile
import random

Input = keras.layers.Input
Model = keras.Model

plot_model = keras.utils.plot_model

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
a = np.load("./model data/pads/d6b4670a206949fda095c7de424e5b04.npy")
print(not a)

True


In [8]:
ids = getDataFromFile("./model data/ids.data")



blackListedPCBs = []

for id in ids:
    pcb = np.load("./model data/pads/" + id + ".npy", allow_pickle=True)
    if len(pcb) == 0:
        blackListedPCBs.append(id)

print(blackListedPCBs)

for blackListed in blackListedPCBs:
    ids.remove(blackListed)

random.shuffle(ids)

['024708e02d7840e495b5d35a115f2e87', '6ae7b8efe6e04b808df28d426b239625', '2a5212d2b61a44169a903f4d9ec78cd8', '900089717c0f4a64ae79d02c34552b2e', 'e7fdc648534d4bc7bc26505e97d51608', '8196b7ca01d745dc950f5a09bd911cf3', '0f3e457667564f31a41dcc54c19fdc41', '88d2b0003a7f4da9852d7586d003d493', '0f110fb23af64c7f964092ffcf8d3658', '502ed64255104f20bf37a2ae2868912e', '05067072071a4ba38bbd4bc2e3f2e382', 'ff1ad3b69a534d15b59b8d3a4282e117', '63a2e2b8ef124e819bb9af56b7dcd816', 'e979911f32cf4cfcbab2e4a4f59dca4d', '11dccf17ea7c4e9d9a3879f2aeba0a58', '4492dfa597574a9b837cfb0e1b70d6ea', 'cd43b439623a492894dad6ab884fe924', 'b79ccc4cebc54ff7bfc606b00038e1e5', 'e887dced2b7a44d7aa3a433b15d01040', 'e5095b0a331c4773b9afad7aa49cecfc', '3496394626c54019aba98676eacf65ab', '2b1a2aa3f57041d6ac8748f5d9c1e74e', '086d0fe22605469585fea6954d78e8e3', 'ac13936c2ef74399b88ade0938b5f2cd', '8ebd07cd0099420588031f395d7d1535', '92bcf789d8b340a2b13905479cae57ab', 'bb9a4422af33467fb95e32b9d0a29de4', '793f3c241c474aaab553e97ac4

In [9]:
myGen = DataGenerator(list_IDs = ["000a5fc5e50b4009bbb09756d16790a8", "00a4d405afd84d5c8246ea1bea68fad1", "00b0bbb4728f49a5b4c40422f96e39a0", "00cb564aa9724961a3001f32ebe10a19"], batch_size = 2)
# print(myGen.loadData(id = "000a5fc5e50b4009bbb09756d16790a8"))

In [10]:
batchSize = 32
validation_split = 0.1
cutoffIndex = int(len(ids)*validation_split)

encoder_input = Input(shape=(None,8,))
decoder_input = Input(shape=(None,8,))
pad_out = autoencoder([encoder_input, decoder_input])
model = Model([encoder_input, decoder_input], pad_out)

trainIds = ids[cutoffIndex:]
valIds = ids[:cutoffIndex]
trainData = DataGenerator(trainIds, batch_size = batchSize)
valData = DataGenerator(valIds, batch_size = batchSize)

In [11]:
keras.utils.plot_model(model, "model.png", show_shapes=True)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [12]:
model.compile(optimizer="rmsprop", loss='categorical_crossentropy', run_eagerly=True)
model.fit(x=trainData, validation_data = valData, epochs = 10)

Epoch 1/10


ValueError: Unknown loss function: categorical_loss

In [15]:
dataGen = DataGenerator([])
# print(dataGen.data_generation(["d6b4670a206949fda095c7de424e5b04"]))

print(dataGen.loadData("d6b4670a206949fda095c7de424e5b04"))
print(np.load("./model data/pads/d6b4670a206949fda095c7de424e5b04.npy", allow_pickle=True))

{'pos': [], 'size': [], 'layer': [], 'net': []}
[]


In [34]:
X, y = dataGen.data_generation(["7e6f3b3b24c0421d9c2ebc60302ce5cd", "00a69a58b8dc4f729784d0b4dad7fb0a"])

print(X["encoder-input"].shape,X["decoder-input"].shape, y.shape)

print(X["encoder-input"])
print(y)

(2, 66, 8) (2, 66, 8) (2, 66, 8)
[[[1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
  [0.000e+00 0.000e+00 1.000e+00 ... 1.210e+02 1.300e+02 1.000e+00]
  [0.000e+00 0.000e+00 1.000e+00 ... 1.210e+02 1.220e+02 2.000e+00]
  ...
  [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
  [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
  [0.000e+00 1.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]

 [[1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
  [0.000e+00 0.000e+00 1.000e+00 ... 4.020e+03 3.158e+03 7.000e+00]
  [0.000e+00 0.000e+00 1.000e+00 ... 4.023e+03 3.158e+03 8.000e+00]
  ...
  [0.000e+00 0.000e+00 1.000e+00 ... 4.032e+03 3.119e+03 1.000e+00]
  [0.000e+00 0.000e+00 1.000e+00 ... 4.037e+03 3.119e+03 4.000e+00]
  [0.000e+00 1.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]]
[[[1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
  [0.000e+00 0.000e+00 1.000e+00 ... 1.210e+02 1.300e+02 1.000e+00]